### ISSUE TITLE
Кодът тук не отразява актуалното състояние на портала

### ISSUE THREAD

**Issue by yurukov** [governmentbg/pitay-gov-bg#4]
Докато търсех кода за промяна, която смятам, че е нужна, открих, че всъщност порталът за запитвания по ЗДОИ върви с различен код от публикувания тук. Един белег за това е валидацията на името на заявителя. Докато на сайта при въвеждане само на собствено име и фамилия връща грешка _"Моля, въведете Име ,Презиме ,Фамилия!"_, такава валидация не може да бъде намерена в този код. Единствената проверка е тук и то дали полето е попълнено:

https://github.com/governmentbg/pitay-gov-bg/blob/e0c302ec2f428c9546046123ad526674eff5a33e/PDoi/src/main/java/indexbg/pdoi/bean/ApplicationForm.java#L307-L310

Валидация дали името е правилно е добра идея, но следва да се позволят само две имена, защото има български граждани без бащино име, особено такива родени в чужбина и чуждестранни граждани. 

Работи ли сайта с друг код или просто промените тук не са още качени? Не виждам такава валидация в по-стари версии.

**Comment by krasig** [comment]
Да. Актуалния код не е качен все още.

**Comment by mitio** [comment]
@krasig Можете ли да дадете ориентир кога се очаква да бъде качен този код?

**Comment by ignisf** [comment]
Ако се очаква одобрение от страна на МС – то е дадено още със спецификацията.

**Comment by krasig** [comment]
Няма необходимост от одобрение. Трябва ми просто време.

**Comment by ignisf** [comment]
От днес кодът в хранилището е обновен https://github.com/governmentbg/pitay-gov-bg/commit/ada3ccdf821cede0ad37ec3aacad80c2d50a665a
